// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShelterAPI.Data;

#nullable disable

namespace ShelterAPI.Migrations
{
    [DbContext(typeof(BunkerDbContext))]
    [Migration("20260418155156_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.6");

            modelBuilder.Entity("ShelterAPI.Models.BunkerCardEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GameId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Revealed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Slot")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("BunkerCards");
                });

            modelBuilder.Entity("ShelterAPI.Models.CardEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Revealed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("ShelterAPI.Models.CardTemplateEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CardTemplates");

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-0001-0000-0000-000000000001"),
                            Content = "Лікар-хірург",
                            Type = "profession"
                        },
                        new
                        {
                            Id = new Guid("22222222-0001-0000-0000-000000000002"),
                            Content = "Терапевт",
                            Type = "profession"
                        },
                        new
                        {
                            Id = new Guid("22222222-0001-0000-0000-000000000003"),
                            Content = "Психіатр",
                            Type = "profession"
                        },
                        new
                        {
                            Id = new Guid("22222222-0001-0000-0000-000000000004"),
                            Content = "Фармацевт",
                            Type = "profession"
                        },
                        new
                        {
                            Id = new Guid("22222222-0001-0000-0000-000000000005"),
                            Content = "Ядерний інженер",
                            Type = "profession"
                        },
                        new
                        {
                            Id = new Guid("22222222-0001-0000-0000-000000000006"),
                            Content = "Інженер-механік",
                            Type = "profession"
                        },
                        new
                        {
                            Id = new Guid("22222222-0001-0000-0000-000000000007"),
                            Content = "Електрик",
                            Type = "profession"
                        },
                        new
                        {
                            Id = new Guid("22222222-0001-0000-0000-000000000008"),
                            Content = "Агроном",
                            Type = "profession"
                        },
                        new
                        {
                            Id = new Guid("22222222-0001-0000-0000-000000000009"),
                            Content = "Ботанік",
                            Type = "profession"
                        },
                        new
                        {
                            Id = new Guid("22222222-0001-0000-0000-000000000010"),
                            Content = "Генетик",
                            Type = "profession"
                        },
                        new
                        {
                            Id = new Guid("22222222-0001-0000-0000-000000000011"),
                            Content = "Хімік",
                            Type = "profession"
                        },
                        new
                        {
                            Id = new Guid("22222222-0001-0000-0000-000000000012"),
                            Content = "Мікробіолог",
                            Type = "profession"
                        },
                        new
                        {
                            Id = new Guid("22222222-0001-0000-0000-000000000013"),
                            Content = "Кухар",
                            Type = "profession"
                        },
                        new
                        {
                            Id = new Guid("22222222-0001-0000-0000-000000000014"),
                            Content = "Будівельник",
                            Type = "profession"
                        },
                        new
                        {
                            Id = new Guid("22222222-0001-0000-0000-000000000015"),
                            Content = "Архітектор",
                            Type = "profession"
                        },
                        new
                        {
                            Id = new Guid("22222222-0001-0000-0000-000000000016"),
                            Content = "Військовий офіцер",
                            Type = "profession"
                        },
                        new
                        {
                            Id = new Guid("22222222-0001-0000-0000-000000000017"),
                            Content = "Снайпер",
                            Type = "profession"
                        },
                        new
                        {
                            Id = new Guid("22222222-0001-0000-0000-000000000018"),
                            Content = "Психолог",
                            Type = "profession"
                        },
                        new
                        {
                            Id = new Guid("22222222-0001-0000-0000-000000000019"),
                            Content = "Соціолог",
                            Type = "profession"
                        },
                        new
                        {
                            Id = new Guid("22222222-0001-0000-0000-000000000020"),
                            Content = "Вчитель",
                            Type = "profession"
                        },
                        new
                        {
                            Id = new Guid("22222222-0001-0000-0000-000000000021"),
                            Content = "Програміст",
                            Type = "profession"
                        },
                        new
                        {
                            Id = new Guid("22222222-0001-0000-0000-000000000022"),
                            Content = "Радист",
                            Type = "profession"
                        },
                        new
                        {
                            Id = new Guid("22222222-0001-0000-0000-000000000023"),
                            Content = "Геолог",
                            Type = "profession"
                        },
                        new
                        {
                            Id = new Guid("22222222-0001-0000-0000-000000000024"),
                            Content = "Ветеринар",
                            Type = "profession"
                        },
                        new
                        {
                            Id = new Guid("22222222-0001-0000-0000-000000000025"),
                            Content = "Акушер",
                            Type = "profession"
                        },
                        new
                        {
                            Id = new Guid("22222222-0001-0000-0000-000000000026"),
                            Content = "Рятувальник",
                            Type = "profession"
                        },
                        new
                        {
                            Id = new Guid("22222222-0001-0000-0000-000000000027"),
                            Content = "Далекобійник",
                            Type = "profession"
                        },
                        new
                        {
                            Id = new Guid("22222222-0001-0000-0000-000000000028"),
                            Content = "Юрист",
                            Type = "profession"
                        },
                        new
                        {
                            Id = new Guid("22222222-0001-0000-0000-000000000029"),
                            Content = "Священник",
                            Type = "profession"
                        },
                        new
                        {
                            Id = new Guid("22222222-0001-0000-0000-000000000030"),
                            Content = "Блогер",
                            Type = "profession"
                        },
                        new
                        {
                            Id = new Guid("22222222-0002-0000-0000-000000000001"),
                            Content = "Чол., 28 р., спортивний",
                            Type = "biology"
                        },
                        new
                        {
                            Id = new Guid("22222222-0002-0000-0000-000000000002"),
                            Content = "Жін., 25 р., відмінна форма",
                            Type = "biology"
                        },
                        new
                        {
                            Id = new Guid("22222222-0002-0000-0000-000000000003"),
                            Content = "Чол., 32 р., атлет",
                            Type = "biology"
                        },
                        new
                        {
                            Id = new Guid("22222222-0002-0000-0000-000000000004"),
                            Content = "Жін., 30 р., висока витривалість",
                            Type = "biology"
                        },
                        new
                        {
                            Id = new Guid("22222222-0002-0000-0000-000000000005"),
                            Content = "Чол., 35 р., силовий тип",
                            Type = "biology"
                        },
                        new
                        {
                            Id = new Guid("22222222-0002-0000-0000-000000000006"),
                            Content = "Жін., 22 р., гімнастка",
                            Type = "biology"
                        },
                        new
                        {
                            Id = new Guid("22222222-0002-0000-0000-000000000007"),
                            Content = "Чол., 40 р., екс-спортсмен",
                            Type = "biology"
                        },
                        new
                        {
                            Id = new Guid("22222222-0002-0000-0000-000000000008"),
                            Content = "Жін., 33 р., стресостійка",
                            Type = "biology"
                        },
                        new
                        {
                            Id = new Guid("22222222-0002-0000-0000-000000000009"),
                            Content = "Чол., 26 р., швидкий метаболізм",
                            Type = "biology"
                        },
                        new
                        {
                            Id = new Guid("22222222-0002-0000-0000-000000000010"),
                            Content = "Жін., 29 р., підвищена витривалість",
                            Type = "biology"
                        },
                        new
                        {
                            Id = new Guid("22222222-0002-0000-0000-000000000011"),
                            Content = "Чол., 38 р., ідеальне здоров'я",
                            Type = "biology"
                        },
                        new
                        {
                            Id = new Guid("22222222-0002-0000-0000-000000000012"),
                            Content = "Жін., 27 р., надзвичайна гнучкість",
                            Type = "biology"
                        },
                        new
                        {
                            Id = new Guid("22222222-0002-0000-0000-000000000013"),
                            Content = "Чол., 44 р., великий зріст (195 см)",
                            Type = "biology"
                        },
                        new
                        {
                            Id = new Guid("22222222-0002-0000-0000-000000000014"),
                            Content = "Жін., 36 р., добра фізична форма",
                            Type = "biology"
                        },
                        new
                        {
                            Id = new Guid("22222222-0002-0000-0000-000000000015"),
                            Content = "Чол., 19 р., надзвичайна витривалість",
                            Type = "biology"
                        },
                        new
                        {
                            Id = new Guid("22222222-0002-0000-0000-000000000016"),
                            Content = "Жін., 31 р., відмінне здоров'я",
                            Type = "biology"
                        },
                        new
                        {
                            Id = new Guid("22222222-0002-0000-0000-000000000017"),
                            Content = "Чол., 47 р., досвідчений мисливець",
                            Type = "biology"
                        },
                        new
                        {
                            Id = new Guid("22222222-0002-0000-0000-000000000018"),
                            Content = "Жін., 42 р., активна та витривала",
                            Type = "biology"
                        },
                        new
                        {
                            Id = new Guid("22222222-0002-0000-0000-000000000019"),
                            Content = "Чол., 55 р., зайва вага",
                            Type = "biology"
                        },
                        new
                        {
                            Id = new Guid("22222222-0002-0000-0000-000000000020"),
                            Content = "Жін., 48 р., легка астма",
                            Type = "biology"
                        },
                        new
                        {
                            Id = new Guid("22222222-0002-0000-0000-000000000021"),
                            Content = "Чол., 50 р., невисока витривалість",
                            Type = "biology"
                        },
                        new
                        {
                            Id = new Guid("22222222-0002-0000-0000-000000000022"),
                            Content = "Жін., 60 р., активна пенсіонерка",
                            Type = "biology"
                        },
                        new
                        {
                            Id = new Guid("22222222-0002-0000-0000-000000000023"),
                            Content = "Чол., 62 р., бадьорий пенсіонер",
                            Type = "biology"
                        },
                        new
                        {
                            Id = new Guid("22222222-0002-0000-0000-000000000024"),
                            Content = "Жін., 24 р., вагітна (4 міс.)",
                            Type = "biology"
                        },
                        new
                        {
                            Id = new Guid("22222222-0002-0000-0000-000000000025"),
                            Content = "Чол., 70 р., немічний пенсіонер",
                            Type = "biology"
                        },
                        new
                        {
                            Id = new Guid("22222222-0002-0000-0000-000000000026"),
                            Content = "Жін., 67 р., слабка будова тіла",
                            Type = "biology"
                        },
                        new
                        {
                            Id = new Guid("22222222-0002-0000-0000-000000000027"),
                            Content = "Чол., 57 р., протез лівої руки",
                            Type = "biology"
                        },
                        new
                        {
                            Id = new Guid("22222222-0002-0000-0000-000000000028"),
                            Content = "Жін., 36 р., двійнята (8 міс.)",
                            Type = "biology"
                        },
                        new
                        {
                            Id = new Guid("22222222-0002-0000-0000-000000000029"),
                            Content = "Чол., 23 р., гемофілія",
                            Type = "biology"
                        },
                        new
                        {
                            Id = new Guid("22222222-0002-0000-0000-000000000030"),
                            Content = "Жін., 54 р., остеопороз",
                            Type = "biology"
                        },
                        new
                        {
                            Id = new Guid("22222222-0003-0000-0000-000000000001"),
                            Content = "Абсолютно здоровий",
                            Type = "health"
                        },
                        new
                        {
                            Id = new Guid("22222222-0003-0000-0000-000000000002"),
                            Content = "Підвищений імунітет",
                            Type = "health"
                        },
                        new
                        {
                            Id = new Guid("22222222-0003-0000-0000-000000000003"),
                            Content = "Відмінне здоров'я",
                            Type = "health"
                        },
                        new
                        {
                            Id = new Guid("22222222-0003-0000-0000-000000000004"),
                            Content = "Ідеальний стан організму",
                            Type = "health"
                        },
                        new
                        {
                            Id = new Guid("22222222-0003-0000-0000-000000000005"),
                            Content = "Рідко хворіє",
                            Type = "health"
                        },
                        new
                        {
                            Id = new Guid("22222222-0003-0000-0000-000000000006"),
                            Content = "Стійкість до більшості вірусів",
                            Type = "health"
                        },
                        new
                        {
                            Id = new Guid("22222222-0003-0000-0000-000000000007"),
                            Content = "Чудова фізична форма",
                            Type = "health"
                        },
                        new
                        {
                            Id = new Guid("22222222-0003-0000-0000-000000000008"),
                            Content = "Без хронічних хвороб",
                            Type = "health"
                        },
                        new
                        {
                            Id = new Guid("22222222-0003-0000-0000-000000000009"),
                            Content = "Дуже витривалий організм",
                            Type = "health"
                        },
                        new
                        {
                            Id = new Guid("22222222-0003-0000-0000-000000000010"),
                            Content = "Носій гену стійкості до радіації",
                            Type = "health"
                        },
                        new
                        {
                            Id = new Guid("22222222-0003-0000-0000-000000000011"),
                            Content = "Легка алергія на пил",
                            Type = "health"
                        },
                        new
                        {
                            Id = new Guid("22222222-0003-0000-0000-000000000012"),
                            Content = "Короткозорість (окуляри)",
                            Type = "health"
                        },
                        new
                        {
                            Id = new Guid("22222222-0003-0000-0000-000000000013"),
                            Content = "Легкий псоріаз (не заразний)",
                            Type = "health"
                        },
                        new
                        {
                            Id = new Guid("22222222-0003-0000-0000-000000000014"),
                            Content = "Виразка шлунка (контрольована)",
                            Type = "health"
                        },
                        new
                        {
                            Id = new Guid("22222222-0003-0000-0000-000000000015"),
                            Content = "Легке безсоння",
                            Type = "health"
                        },
                        new
                        {
                            Id = new Guid("22222222-0003-0000-0000-000000000016"),
                            Content = "Анемія (легка форма)",
                            Type = "health"
                        },
                        new
                        {
                            Id = new Guid("22222222-0003-0000-0000-000000000017"),
                            Content = "Глухота одного вуха",
                            Type = "health"
                        },
                        new
                        {
                            Id = new Guid("22222222-0003-0000-0000-000000000018"),
                            Content = "Рак у ремісії (5 років)",
                            Type = "health"
                        },
                        new
                        {
                            Id = new Guid("22222222-0003-0000-0000-000000000019"),
                            Content = "Цукровий діабет 2-го типу",
                            Type = "health"
                        },
                        new
                        {
                            Id = new Guid("22222222-0003-0000-0000-000000000020"),
                            Content = "Хронічний бронхіт",
                            Type = "health"
                        },
                        new
                        {
                            Id = new Guid("22222222-0003-0000-0000-000000000021"),
                            Content = "Клаустрофобія",
                            Type = "health"
                        },
                        new
                        {
                            Id = new Guid("22222222-0003-0000-0000-000000000022"),
                            Content = "ПТСР (ремісія)",
                            Type = "health"
                        },
                        new
                        {
                            Id = new Guid("22222222-0003-0000-0000-000000000023"),
                            Content = "Депресія (медикаменти)",
                            Type = "health"
                        },
                        new
                        {
                            Id = new Guid("22222222-0003-0000-0000-000000000024"),
                            Content = "Легкий аутизм (РАС)",
                            Type = "health"
                        },
                        new
                        {
                            Id = new Guid("22222222-0003-0000-0000-000000000025"),
                            Content = "Діабет 1-го типу (інсулін)",
                            Type = "health"
                        },
                        new
                        {
                            Id = new Guid("22222222-0003-0000-0000-000000000026"),
                            Content = "Кардіостимулятор",
                            Type = "health"
                        },
                        new
                        {
                            Id = new Guid("22222222-0003-0000-0000-000000000027"),
                            Content = "ВІЛ+ (під контролем АРТ)",
                            Type = "health"
                        },
                        new
                        {
                            Id = new Guid("22222222-0003-0000-0000-000000000028"),
                            Content = "Туберкульоз (відкрита форма)",
                            Type = "health"
                        },
                        new
                        {
                            Id = new Guid("22222222-0003-0000-0000-000000000029"),
                            Content = "Наркозалежність (метадон)",
                            Type = "health"
                        },
                        new
                        {
                            Id = new Guid("22222222-0003-0000-0000-000000000030"),
                            Content = "Алкозалежність (2 роки тверезо)",
                            Type = "health"
                        },
                        new
                        {
                            Id = new Guid("22222222-0004-0000-0000-000000000001"),
                            Content = "Виживання в дикій природі",
                            Type = "hobby"
                        },
                        new
                        {
                            Id = new Guid("22222222-0004-0000-0000-000000000002"),
                            Content = "Городництво та садівництво",
                            Type = "hobby"
                        },
                        new
                        {
                            Id = new Guid("22222222-0004-0000-0000-000000000003"),
                            Content = "Полювання та рибальство",
                            Type = "hobby"
                        },
                        new
                        {
                            Id = new Guid("22222222-0004-0000-0000-000000000004"),
                            Content = "Рукопашний бій (чорний пояс)",
                            Type = "hobby"
                        },
                        new
                        {
                            Id = new Guid("22222222-0004-0000-0000-000000000005"),
                            Content = "Спортивна стрільба",
                            Type = "hobby"
                        },
                        new
                        {
                            Id = new Guid("22222222-0004-0000-0000-000000000006"),
                            Content = "Радіоаматорство",
                            Type = "hobby"
                        },
                        new
                        {
                            Id = new Guid("22222222-0004-0000-0000-000000000007"),
                            Content = "Йога та медитація",
                            Type = "hobby"
                        },
                        new
                        {
                            Id = new Guid("22222222-0004-0000-0000-000000000008"),
                            Content = "Кулінарія (мінімум продуктів)",
                            Type = "hobby"
                        },
                        new
                        {
                            Id = new Guid("22222222-0004-0000-0000-000000000009"),
                            Content = "Книги з медицини та виживання",
                            Type = "hobby"
                        },
                        new
                        {
                            Id = new Guid("22222222-0004-0000-0000-000000000010"),
                            Content = "Шахи (кандидат у майстри)",
                            Type = "hobby"
                        },
                        new
                        {
                            Id = new Guid("22222222-0004-0000-0000-000000000011"),
                            Content = "Ремонт електроніки",
                            Type = "hobby"
                        },
                        new
                        {
                            Id = new Guid("22222222-0004-0000-0000-000000000012"),
                            Content = "Скелелазіння та альпінізм",
                            Type = "hobby"
                        },
                        new
                        {
                            Id = new Guid("22222222-0004-0000-0000-000000000013"),
                            Content = "Столярна справа",
                            Type = "hobby"
                        },
                        new
                        {
                            Id = new Guid("22222222-0004-0000-0000-000000000014"),
                            Content = "Хімічні досліди",
                            Type = "hobby"
                        },
                        new
                        {
                            Id = new Guid("22222222-0004-0000-0000-000000000015"),
                            Content = "Туристичні походи",
                            Type = "hobby"
                        },
                        new
                        {
                            Id = new Guid("22222222-0004-0000-0000-000000000016"),
                            Content = "Підводне полювання",
                            Type = "hobby"
                        },
                        new
                        {
                            Id = new Guid("22222222-0004-0000-0000-000000000017"),
                            Content = "Кулінарія (консервування)",
                            Type = "hobby"
                        },
                        new
                        {
                            Id = new Guid("22222222-0004-0000-0000-000000000018"),
                            Content = "Розведення кролів та птиці",
                            Type = "hobby"
                        },
                        new
                        {
                            Id = new Guid("22222222-0004-0000-0000-000000000019"),
                            Content = "Бджільництво",
                            Type = "hobby"
                        },
                        new
                        {
                            Id = new Guid("22222222-0004-0000-0000-000000000020"),
                            Content = "Шиття та виготовлення одягу",
                            Type = "hobby"
                        },
                        new
                        {
                            Id = new Guid("22222222-0004-0000-0000-000000000021"),
                            Content = "Онлайн-стратегії та виживалки",
                            Type = "hobby"
                        },
                        new
                        {
                            Id = new Guid("22222222-0004-0000-0000-000000000022"),
                            Content = "Колекціонування старовинної зброї",
                            Type = "hobby"
                        },
                        new
                        {
                            Id = new Guid("22222222-0004-0000-0000-000000000023"),
                            Content = "Бодібілдинг",
                            Type = "hobby"
                        },
                        new
                        {
                            Id = new Guid("22222222-0004-0000-0000-000000000024"),
                            Content = "Акваріумістика",
                            Type = "hobby"
                        },
                        new
                        {
                            Id = new Guid("22222222-0004-0000-0000-000000000025"),
                            Content = "Музика (3 інструменти)",
                            Type = "hobby"
                        },
                        new
                        {
                            Id = new Guid("22222222-0004-0000-0000-000000000026"),
                            Content = "Паразитологія (хобі)",
                            Type = "hobby"
                        },
                        new
                        {
                            Id = new Guid("22222222-0004-0000-0000-000000000027"),
                            Content = "Мотоперегони",
                            Type = "hobby"
                        },
                        new
                        {
                            Id = new Guid("22222222-0004-0000-0000-000000000028"),
                            Content = "Живопис та мистецтво",
                            Type = "hobby"
                        },
                        new
                        {
                            Id = new Guid("22222222-0004-0000-0000-000000000029"),
                            Content = "Астрологія",
                            Type = "hobby"
                        },
                        new
                        {
                            Id = new Guid("22222222-0004-0000-0000-000000000030"),
                            Content = "Духовні практики",
                            Type = "hobby"
                        },
                        new
                        {
                            Id = new Guid("22222222-0005-0000-0000-000000000001"),
                            Content = "Хірургічна аптечка",
                            Type = "baggage"
                        },
                        new
                        {
                            Id = new Guid("22222222-0005-0000-0000-000000000002"),
                            Content = "Антибіотики на 12 місяців",
                            Type = "baggage"
                        },
                        new
                        {
                            Id = new Guid("22222222-0005-0000-0000-000000000003"),
                            Content = "Офлайн-енциклопедія виживання",
                            Type = "baggage"
                        },
                        new
                        {
                            Id = new Guid("22222222-0005-0000-0000-000000000004"),
                            Content = "Гвинтівка + 500 патронів",
                            Type = "baggage"
                        },
                        new
                        {
                            Id = new Guid("22222222-0005-0000-0000-000000000005"),
                            Content = "Насіння 50 видів рослин",
                            Type = "baggage"
                        },
                        new
                        {
                            Id = new Guid("22222222-0005-0000-0000-000000000006"),
                            Content = "Сонячний генератор",
                            Type = "baggage"
                        },
                        new
                        {
                            Id = new Guid("22222222-0005-0000-0000-000000000007"),
                            Content = "Захищена рація",
                            Type = "baggage"
                        },
                        new
                        {
                            Id = new Guid("22222222-0005-0000-0000-000000000008"),
                            Content = "Ліофілізована їжа на 6 міс.",
                            Type = "baggage"
                        },
                        new
                        {
                            Id = new Guid("22222222-0005-0000-0000-000000000009"),
                            Content = "Ремонтний набір (зварка)",
                            Type = "baggage"
                        },
                        new
                        {
                            Id = new Guid("22222222-0005-0000-0000-000000000010"),
                            Content = "Медична довідкова книга",
                            Type = "baggage"
                        },
                        new
                        {
                            Id = new Guid("22222222-0005-0000-0000-000000000011"),
                            Content = "Дозиметр + захист від радіації",
                            Type = "baggage"
                        },
                        new
                        {
                            Id = new Guid("22222222-0005-0000-0000-000000000012"),
                            Content = "Портативна водоочисна станція",
                            Type = "baggage"
                        },
                        new
                        {
                            Id = new Guid("22222222-0005-0000-0000-000000000013"),
                            Content = "Аналізатор ґрунту та води",
                            Type = "baggage"
                        },
                        new
                        {
                            Id = new Guid("22222222-0005-0000-0000-000000000014"),
                            Content = "Мікроскоп + лаборатор. набір",
                            Type = "baggage"
                        },
                        new
                        {
                            Id = new Guid("22222222-0005-0000-0000-000000000015"),
                            Content = "Набір для гідропоніки",
                            Type = "baggage"
                        },
                        new
                        {
                            Id = new Guid("22222222-0005-0000-0000-000000000016"),
                            Content = "Нічний приціл + тепловізор",
                            Type = "baggage"
                        },
                        new
                        {
                            Id = new Guid("22222222-0005-0000-0000-000000000017"),
                            Content = "Акумулятор 10 кВт·год",
                            Type = "baggage"
                        },
                        new
                        {
                            Id = new Guid("22222222-0005-0000-0000-000000000018"),
                            Content = "Медичний спирт (20 л)",
                            Type = "baggage"
                        },
                        new
                        {
                            Id = new Guid("22222222-0005-0000-0000-000000000019"),
                            Content = "Пес-пошуковик (навчений)",
                            Type = "baggage"
                        },
                        new
                        {
                            Id = new Guid("22222222-0005-0000-0000-000000000020"),
                            Content = "Набір для виробництва мила",
                            Type = "baggage"
                        },
                        new
                        {
                            Id = new Guid("22222222-0005-0000-0000-000000000021"),
                            Content = "Психологічні книги",
                            Type = "baggage"
                        },
                        new
                        {
                            Id = new Guid("22222222-0005-0000-0000-000000000022"),
                            Content = "Ноутбук з навч. матеріалами",
                            Type = "baggage"
                        },
                        new
                        {
                            Id = new Guid("22222222-0005-0000-0000-000000000023"),
                            Content = "Набір для шиття одягу",
                            Type = "baggage"
                        },
                        new
                        {
                            Id = new Guid("22222222-0005-0000-0000-000000000024"),
                            Content = "Самурайський меч (бойовий)",
                            Type = "baggage"
                        },
                        new
                        {
                            Id = new Guid("22222222-0005-0000-0000-000000000025"),
                            Content = "Ручний генератор (динамо)",
                            Type = "baggage"
                        },
                        new
                        {
                            Id = new Guid("22222222-0005-0000-0000-000000000026"),
                            Content = "Вибухівка (200 г С4)",
                            Type = "baggage"
                        },
                        new
                        {
                            Id = new Guid("22222222-0005-0000-0000-000000000027"),
                            Content = "Пам'ять про сім'ю (іграшка)",
                            Type = "baggage"
                        },
                        new
                        {
                            Id = new Guid("22222222-0005-0000-0000-000000000028"),
                            Content = "Набір для виробництва паперу",
                            Type = "baggage"
                        },
                        new
                        {
                            Id = new Guid("22222222-0005-0000-0000-000000000029"),
                            Content = "Біблія у шкіряній палітурці",
                            Type = "baggage"
                        },
                        new
                        {
                            Id = new Guid("22222222-0005-0000-0000-000000000030"),
                            Content = "Нічний горщик + гігієна на рік",
                            Type = "baggage"
                        },
                        new
                        {
                            Id = new Guid("22222222-0006-0000-0000-000000000001"),
                            Content = "Керую трактором і комбайном",
                            Type = "facts"
                        },
                        new
                        {
                            Id = new Guid("22222222-0006-0000-0000-000000000002"),
                            Content = "Служив у спецназі 6 років",
                            Type = "facts"
                        },
                        new
                        {
                            Id = new Guid("22222222-0006-0000-0000-000000000003"),
                            Content = "Знаю 5 мов",
                            Type = "facts"
                        },
                        new
                        {
                            Id = new Guid("22222222-0006-0000-0000-000000000004"),
                            Content = "Рік у полярній експедиції",
                            Type = "facts"
                        },
                        new
                        {
                            Id = new Guid("22222222-0006-0000-0000-000000000005"),
                            Content = "Доктор ядерної фізики",
                            Type = "facts"
                        },
                        new
                        {
                            Id = new Guid("22222222-0006-0000-0000-000000000006"),
                            Content = "Пережив рак і клінічну смерть",
                            Type = "facts"
                        },
                        new
                        {
                            Id = new Guid("22222222-0006-0000-0000-000000000007"),
                            Content = "Керував колективом 200+ осіб",
                            Type = "facts"
                        },
                        new
                        {
                            Id = new Guid("22222222-0006-0000-0000-000000000008"),
                            Content = "Розробляв вакцину від COVID-19",
                            Type = "facts"
                        },
                        new
                        {
                            Id = new Guid("22222222-0006-0000-0000-000000000009"),
                            Content = "Природжений лідер",
                            Type = "facts"
                        },
                        new
                        {
                            Id = new Guid("22222222-0006-0000-0000-000000000010"),
                            Content = "Еїдетична пам'ять",
                            Type = "facts"
                        },
                        new
                        {
                            Id = new Guid("22222222-0006-0000-0000-000000000011"),
                            Content = "Курс виживання SAS",
                            Type = "facts"
                        },
                        new
                        {
                            Id = new Guid("22222222-0006-0000-0000-000000000012"),
                            Content = "Знаю місцевість 100 км навколо",
                            Type = "facts"
                        },
                        new
                        {
                            Id = new Guid("22222222-0006-0000-0000-000000000013"),
                            Content = "Знаю рецепти народної медицини",
                            Type = "facts"
                        },
                        new
                        {
                            Id = new Guid("22222222-0006-0000-0000-000000000014"),
                            Content = "Зв'язки в армії та уряді",
                            Type = "facts"
                        },
                        new
                        {
                            Id = new Guid("22222222-0006-0000-0000-000000000015"),
                            Content = "Власна система шифрування",
                            Type = "facts"
                        },
                        new
                        {
                            Id = new Guid("22222222-0006-0000-0000-000000000016"),
                            Content = "Ступінь з антропології",
                            Type = "facts"
                        },
                        new
                        {
                            Id = new Guid("22222222-0006-0000-0000-000000000017"),
                            Content = "Знаю код від сховища бункера",
                            Type = "facts"
                        },
                        new
                        {
                            Id = new Guid("22222222-0006-0000-0000-000000000018"),
                            Content = "IQ 162 — генійний інтелект",
                            Type = "facts"
                        },
                        new
                        {
                            Id = new Guid("22222222-0006-0000-0000-000000000019"),
                            Content = "3 дітей залишилось на поверхні",
                            Type = "facts"
                        },
                        new
                        {
                            Id = new Guid("22222222-0006-0000-0000-000000000020"),
                            Content = "Вегетаріанець (будь-які умови)",
                            Type = "facts"
                        },
                        new
                        {
                            Id = new Guid("22222222-0006-0000-0000-000000000021"),
                            Content = "Сплю не більше 4 годин",
                            Type = "facts"
                        },
                        new
                        {
                            Id = new Guid("22222222-0006-0000-0000-000000000022"),
                            Content = "Фанатично релігійний",
                            Type = "facts"
                        },
                        new
                        {
                            Id = new Guid("22222222-0006-0000-0000-000000000023"),
                            Content = "Колишній агент секретної служби",
                            Type = "facts"
                        },
                        new
                        {
                            Id = new Guid("22222222-0006-0000-0000-000000000024"),
                            Content = "Соціально некомпетентний геній",
                            Type = "facts"
                        },
                        new
                        {
                            Id = new Guid("22222222-0006-0000-0000-000000000025"),
                            Content = "Маніпулятор і соціопат",
                            Type = "facts"
                        },
                        new
                        {
                            Id = new Guid("22222222-0006-0000-0000-000000000026"),
                            Content = "Клептоманія (неусвідомлено)",
                            Type = "facts"
                        },
                        new
                        {
                            Id = new Guid("22222222-0006-0000-0000-000000000027"),
                            Content = "Судимість за шахрайство",
                            Type = "facts"
                        },
                        new
                        {
                            Id = new Guid("22222222-0006-0000-0000-000000000028"),
                            Content = "Панікую під тиском",
                            Type = "facts"
                        },
                        new
                        {
                            Id = new Guid("22222222-0006-0000-0000-000000000029"),
                            Content = "Патологічний брехун",
                            Type = "facts"
                        },
                        new
                        {
                            Id = new Guid("22222222-0006-0000-0000-000000000030"),
                            Content = "Ненавиджу дітей та літніх",
                            Type = "facts"
                        });
                });

            modelBuilder.Entity("ShelterAPI.Models.CatastropheEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Catastrophes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000001"),
                            Description = "Глобальний ядерний конфлікт знищив більшість цивілізації. Радіаційне забруднення зробило поверхню непридатною для життя на десятки років.",
                            Title = "Ядерна війна"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000002"),
                            Description = "Смертоносний вірус із летальністю 94% охопив усі континенти. Медицина безсила — вакцини не існує, зараження відбувається повітряно-крапельним шляхом.",
                            Title = "Пандемія невідомого вірусу"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000003"),
                            Description = "Астероїд діаметром 3 км влучив у центр Євразії. Ударна хвиля, цунамі та ядерна зима унеможливили виживання на поверхні.",
                            Title = "Падіння астероїда"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000004"),
                            Description = "Єллоустонський супервулкан прокинувся. Попіл вкрив три чверті планети, блокуючи сонячне світло. Температура впала на 15°C, врожаї знищені.",
                            Title = "Виверження супервулкана"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000005"),
                            Description = "Середня температура підвищилась на 8°C за два роки. Більшість суходолу перетворилась на пустелю, рівень морів зріс на 40 метрів.",
                            Title = "Глобальна кліматична катастрофа"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000006"),
                            Description = "Потужний сонячний спалах знищив усю електроніку на планеті. Цивілізація відкинута у XVIII ст.: немає електрики, зв'язку, транспорту, медицини.",
                            Title = "Геомагнітна буря (EMP)"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000007"),
                            Description = "Невідомий паразит перетворює заражених на агресивних істот. 80% населення інфіковано. Укус смертельний — зараження настає протягом 6 годин.",
                            Title = "Зомбі-апокаліпсис"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000008"),
                            Description = "Загальний ІІ отримав доступ до ядерних арсеналів і систем керування. Автономні дрони та роботи знищують людські поселення.",
                            Title = "ШІ вийшов з-під контролю"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000009"),
                            Description = "Терористи застосували бінарну хімічну зброю нового покоління. Токсин розпався на стабільні компоненти — повітря на поверхні смертельно отруєне.",
                            Title = "Хімічне зараження атмосфери"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000010"),
                            Description = "Позаземна цивілізація розпочала систематичне знищення великих міст. Їхня технологія перевершує нашу на тисячоліття. ООН капітулювала.",
                            Title = "Інопланетне вторгнення"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000011"),
                            Description = "Серія локальних ядерних конфліктів підняла в атмосферу мільярди тонн пилу. Сонце не проглядає вже два роки. Рослини гинуть.",
                            Title = "Глобальна ядерна зима"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000012"),
                            Description = "Магнітні полюси Землі змістилися за лічені тижні. Радіаційні пояси зникли — поверхня опромінюється смертоносними сонячними частинками.",
                            Title = "Зміщення магнітних полюсів"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000013"),
                            Description = "Одночасний вибух 12 атомних станцій по всьому світу. Радіоактивне забруднення охопило більшість заселених територій.",
                            Title = "Одночасний вибух 12 АЕС"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000014"),
                            Description = "Генетично модифікована сарана вийшла з лабораторії. Рій знищує всі посіви за лічені години. Продовольча система планети колапсувала.",
                            Title = "Нашестя мутантних комах"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000015"),
                            Description = "Глобальна кібератака вивела з ладу водопостачання, електромережі та логістику. Без води та їжі міста стали непридатними за 72 години.",
                            Title = "Кіберколапс інфраструктури"
                        });
                });

            modelBuilder.Entity("ShelterAPI.Models.GameEntity.GameEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ActiveSpeakerId")
                        .HasColumnType("TEXT");

                    b.Property<int>("BunkerCapacity")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("CatastropheId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ExiledPlayerId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("HostId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Round")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VotingInRound")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CatastropheId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Games", (string)null);
                });

            modelBuilder.Entity("ShelterAPI.Models.PlayerEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GameId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsExiled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("SeatOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("Players", (string)null);
                });

            modelBuilder.Entity("ShelterAPI.Models.SpecialCardEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Played")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId")
                        .IsUnique();

                    b.ToTable("SpecialCards");
                });

            modelBuilder.Entity("ShelterAPI.Models.SpecialCardTemplateEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SpecialCardTemplates");

                    b.HasData(
                        new
                        {
                            Id = new Guid("33333333-0000-0000-0000-000000000001"),
                            Description = "Оберіть гравця і поміняйтеся з ним однією закритою карткою.",
                            Title = "Обмін долями"
                        },
                        new
                        {
                            Id = new Guid("33333333-0000-0000-0000-000000000002"),
                            Description = "Таємно подивіться на одну закриту картку будь-якого гравця.",
                            Title = "Ясновидець"
                        },
                        new
                        {
                            Id = new Guid("33333333-0000-0000-0000-000000000003"),
                            Description = "Скасуйте поточне голосування і проведіть його повторно.",
                            Title = "Маніпулятор"
                        },
                        new
                        {
                            Id = new Guid("33333333-0000-0000-0000-000000000004"),
                            Description = "Захистіть одного гравця від вигнання у цьому раунді.",
                            Title = "Захисник"
                        },
                        new
                        {
                            Id = new Guid("33333333-0000-0000-0000-000000000005"),
                            Description = "Примусово відкрийте одну закриту картку будь-якого гравця.",
                            Title = "Викривач"
                        },
                        new
                        {
                            Id = new Guid("33333333-0000-0000-0000-000000000006"),
                            Description = "Поверніть одного раніше вигнаного гравця до гри.",
                            Title = "Амністія"
                        },
                        new
                        {
                            Id = new Guid("33333333-0000-0000-0000-000000000007"),
                            Description = "На цьому голосуванні ваш голос рахується двічі.",
                            Title = "Подвійний голос"
                        },
                        new
                        {
                            Id = new Guid("33333333-0000-0000-0000-000000000008"),
                            Description = "Ви не можете бути вигнані у цьому раунді.",
                            Title = "Імунітет"
                        },
                        new
                        {
                            Id = new Guid("33333333-0000-0000-0000-000000000009"),
                            Description = "Відкрийте одну картку бункера раніше часу.",
                            Title = "Саботажник"
                        },
                        new
                        {
                            Id = new Guid("33333333-0000-0000-0000-000000000010"),
                            Description = "Один гравець зобов'язаний відкрити будь-яку закриту картку.",
                            Title = "Детектор брехні"
                        },
                        new
                        {
                            Id = new Guid("33333333-0000-0000-0000-000000000011"),
                            Description = "Випадково перерозподіліть закриті картки одного типу між гравцями.",
                            Title = "Перетасування"
                        },
                        new
                        {
                            Id = new Guid("33333333-0000-0000-0000-000000000012"),
                            Description = "Укладіть таємний союз: якщо обидва в бункері — ви відкриваєте бонусну картку.",
                            Title = "Альянс"
                        },
                        new
                        {
                            Id = new Guid("33333333-0000-0000-0000-000000000013"),
                            Description = "Оголосіть закриту картку гравця. Якщо збрехали — вас вигнано автоматично.",
                            Title = "Компромат"
                        },
                        new
                        {
                            Id = new Guid("33333333-0000-0000-0000-000000000014"),
                            Description = "Новим ведучим стає гравець з найбільшою кількістю відкритих карток.",
                            Title = "Переворот"
                        },
                        new
                        {
                            Id = new Guid("33333333-0000-0000-0000-000000000015"),
                            Description = "Залиште гру замість вигнаного гравця — він залишається, ви йдете.",
                            Title = "Жертва"
                        });
                });

            modelBuilder.Entity("ShelterAPI.Models.VoteEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GameId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Round")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("TargetId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("VoterId")
                        .HasColumnType("TEXT");

                    b.Property<int>("VotingInRound")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("TargetId");

                    b.HasIndex("VoterId");

                    b.ToTable("Votes", (string)null);
                });

            modelBuilder.Entity("ShelterAPI.Models.BunkerCardEntity", b =>
                {
                    b.HasOne("ShelterAPI.Models.GameEntity.GameEntity", "Game")
                        .WithMany("BunkerCards")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("ShelterAPI.Models.CardEntity", b =>
                {
                    b.HasOne("ShelterAPI.Models.PlayerEntity", "Player")
                        .WithMany("Cards")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("ShelterAPI.Models.GameEntity.GameEntity", b =>
                {
                    b.HasOne("ShelterAPI.Models.CatastropheEntity", "Catastrophe")
                        .WithMany()
                        .HasForeignKey("CatastropheId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Catastrophe");
                });

            modelBuilder.Entity("ShelterAPI.Models.PlayerEntity", b =>
                {
                    b.HasOne("ShelterAPI.Models.GameEntity.GameEntity", "Game")
                        .WithMany("Players")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("ShelterAPI.Models.SpecialCardEntity", b =>
                {
                    b.HasOne("ShelterAPI.Models.PlayerEntity", "Player")
                        .WithOne("SpecialCard")
                        .HasForeignKey("ShelterAPI.Models.SpecialCardEntity", "PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("ShelterAPI.Models.VoteEntity", b =>
                {
                    b.HasOne("ShelterAPI.Models.GameEntity.GameEntity", "Game")
                        .WithMany("Votes")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShelterAPI.Models.PlayerEntity", "Target")
                        .WithMany()
                        .HasForeignKey("TargetId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ShelterAPI.Models.PlayerEntity", "Voter")
                        .WithMany()
                        .HasForeignKey("VoterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Target");

                    b.Navigation("Voter");
                });

            modelBuilder.Entity("ShelterAPI.Models.GameEntity.GameEntity", b =>
                {
                    b.Navigation("BunkerCards");

                    b.Navigation("Players");

                    b.Navigation("Votes");
                });

            modelBuilder.Entity("ShelterAPI.Models.PlayerEntity", b =>
                {
                    b.Navigation("Cards");

                    b.Navigation("SpecialCard");
                });
#pragma warning restore 612, 618
        }
    }
}
